// <auto-generated />
namespace LoanOFFER.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fifthmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fifthmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202009221149155_fifth-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
